language: node_js
node_js:
- iojs-v1
sudo: false
cache:
  directories:
  - node_modules
notifications:
  email: false
before_deploy:
- npm config set spin false --global
env:
  global:
  - secure: cbFwxQm/JmvPkjvRsDRMFpAsGV8zrqEqjbYZHUX3tMqiJlZu/tNPQ2Cqbmg0wIOMl42G5Kr3DWA79gOsYilNlMDeALdPFHwMghoTNCdF6OWRi+SdAexKIcvZj/SXJq3N34Vn/r5OUk0MdiqTbgSOaIgXWwXB0KUYWvZt0Y+VRzQ=
deploy:
  provider: npm
  email: kzm@sykosomatic.org
  skip_cleanup: true
  api_key:
    secure: UDUSWZKkobzrv5yhkypHy1BvaTtNqDQ9Kg3Rw+pBiGtORgP+3+f9Wf5yKOQLdM2O5nB5FbsxYh/cNd7FJFvY/z0SGdcm4O5spAetKk2RvA2bcEc2wBcFrqsMnHEPEzR2MJaIjvOZBy5VnfxfcD15pzFaPLjlUHzDQaPQ7M83jKU=
  on:
    branch: master
    repo: zkat/genfun
